### ISSUE TITLE
boost 1.78.0 for darwin target system for arm64 / aarch64 architecture

### ISSUE THREAD

**Issue by matusz** [MarkusJx/prebuilt-boost#11]
Hi!

Are there available boost libraries 1.78.0 for darwin target system for arm64 / aarch64 architecture?

br,
matusz

**Comment by MarkusJx** [comment]
Currently, the libraries are only available for x86 architectures. This was already asked here: https://github.com/MarkusJx/install-boost/discussions/33, but I'll take a look since github now supports M1 runners.

**Comment by MarkusJx** [comment]
I've added boost binaries for version `1.78.0` and target `arm64` for macos 14.
Please verify that the library is working for you

**Comment by MarkusJx** [comment]
Boost version `1.78.0` unfortunately can't be built anymore due to a change in the MacOs SDK: https://github.com/MarkusJx/install-boost/issues/45#issuecomment-2094268593.
ARM builds starting from version `1.81.0` are available though.

Closing this issue in favor of https://github.com/MarkusJx/install-boost/issues/45
