### ISSUE TITLE
Linking statically with binaries on Windows

### ISSUE THREAD

**Issue by devm18426** [MarkusJx/prebuilt-boost#8]
I may be misunderstanding but it would appear that the "static link" binaries that are provided aren't in fact suited for static linking. I've encountered this issue specifically only on Windows (so far).

One clear indication is that the filename of the binaries is missing the `s` specifier. Looking over the Workflow code, it looks like `runtime-link=static` is missing from the build command. This option is, from my understanding, what makes the binaries statically linkable.

Attempting to link with the current binaries leads Boost's auto-linker to fail with a message similar to:

    LINK : fatal error LNK1104: cannot open file 'libboost_python39-vc143-mt-s-x64-1_83.lib'

Looking into `boost-1.83.0-windows-2022-msvc-static-x86.tar.gz` provided by this repo we'll find that the above file indeed does not exist. Instead we'll find `libboost_python39-vc143-mt-s-x64-1_83.lib` (`s` missing).

**Comment by MarkusJx** [comment]
If you actually want to use statically linked libraries (using the `/MT` compiler option) instead of dynamically linked libraries (`/MD`), well, that's kind of not supported. The `link`  option inside the `install-boost` action  actually refers to how the binaries have been linked during build (so if the result has been either `.dll`s or `.lib`s).

I've disabled statically linked libraries some time ago due to memory constraints on the windows runners, both mac and linux still have both options available. Also, dynamically linked libraries [seem to be the better option](https://stackoverflow.com/a/757537), but I'm not judging.

If you just want `.lib`s instead of `.dll`s, that's supported by the action, as mentioned earlier. If you are still interested in linking the libraries statically, I could look into providing those binaries, but I'm not going to guarantee anything as this may not work or may be a huge hassle to do.

**Comment by devm18426** [comment]
Ok you've given me some homework and thinking to do. My end goal is packaging and deploying a Python package with a native extension that requires Boost. So I'm looking for the lowest profile output possible. Static linking made the most sense but I'll rethink. 

One thing I still don't quite understand is how the Windows `lib`s provided can be used. Are they a drop in replacement for DLLs?

Thanks

**Comment by MarkusJx** [comment]
The application with the lowest profile will be produced by dynamically linking the libraries at runtime, as some system `dll`s are being reused (I guess that's the whole point of `dll`s). This does not mean your application will use any of boost's `dll`s (or rather `dll`s containing boost "code"), you'll still link against static libs at build time, but those libs themselves (and your application itself) link against some system `dll`s rather than copying the contents of the system `lib`s (which contain the same code as the `dll`s) into your application. This is rather confusing to explain. Thank you someone for using the same nomenclature for two completely different things, I guess.

But I'd suggest to statically link against the boost libraries, which will dynamically link to some system `dll`s at runtime, and your program will do so, too. Keep in mind that there seem to be [issues with that approach](https://stackoverflow.com/a/31226997), but that should be solvable.

Also, I am not an expert on this topic, especially since I've moved on from developing C++ several years ago, I'm just maintaining this actions as long as people need it.

**Comment by MarkusJx** [comment]
Closing as the issue doesn't seem to be relevant anymore.
